"""empty message

Revision ID: 0493f6466b68
Revises: bf0cbf983ef5
Create Date: 2020-04-10 18:40:23.387479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0493f6466b68'
down_revision = 'bf0cbf983ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('preview_image_url', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('price', sa.String(length=20), nullable=False))
    op.add_column('classes', sa.Column('youtube_id', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'youtube_id')
    op.drop_column('classes', 'price')
    op.drop_column('classes', 'preview_image_url')
    # ### end Alembic commands ###
