"""empty message

Revision ID: bf0cbf983ef5
Revises: f74803a27b71
Create Date: 2020-04-10 18:33:02.331882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0cbf983ef5'
down_revision = 'f74803a27b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.add_column('classes', sa.Column('free', sa.Boolean(), nullable=False))
    op.add_column('classes', sa.Column('price', sa.String(length=20), nullable=False))
    op.add_column('classes', sa.Column('youtube_id', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'youtube_id')
    op.drop_column('classes', 'price')
    op.drop_column('classes', 'free')
    op.drop_table('booking')
    # ### end Alembic commands ###
